/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GenfosisScoreBox: typeof import('./src/components/homepage/components/GenfosisScoreBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    StatsListView: typeof import('./src/components/stats/details/StatsListView.vue')['default']
    StepCountBox: typeof import('./src/components/homepage/components/StepCountBox.vue')['default']
  }
}
